# https://forrestjacobs.com/keeping-nixos-systems-up-to-date-with-github-actions/
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 4 * * 0-6' # runs everyday at 4am

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}
      - name: Merge
        run: "gh pr merge --auto --merge ${{ steps.update.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{secrets.GH_ACTION_TOKEN}}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
           
